backend:
  name: github
  repo: atimwu/astro-blog-starter-template # 你的 GitHub 帳號/儲存庫名稱
  branch: main # 預設分支

media_folder: "public/blog-placeholder" # 圖片上傳儲存的位置
public_folder: "/blog-placeholder" # 圖片在網站上的讀取路徑

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog" # Astro 文章存放的路徑
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Pub Date", name: "pubDate", widget: "datetime" }
      - { label: "Hero Image", name: "heroImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
